# Generated by Django 5.1.2 on 2025-11-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_mcqhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcqhistory',
            name='mcq_data',
            field=models.TextField(),
        ),
    ]
